version: "3"
services:
    db:
      container_name: db2
      image: mongo
      ports:
       - "27017:27017"  
      volumes:
       - ./.data:/data/db2
    api:
      container_name: api2
      build: .
      ports :
       - "3000:3000"
      volumes:
        - ./:/home/node/app
